### PR TITLE
fix position access error

### PR DESCRIPTION
**Pull request by lerit**
position is a subproperty of _value,cash and now_account_value belongs to  _value.position
maybe error since:https://github.com/microsoft/qlib/pull/1120

### CODE REVIEW

**Comment by you-n-g** [comment]
Thanks for your contributions! 

Please fix the CI error.

**Comment by you-n-g** [comment]
Thanks for your contribution.
This reflex another flaw of our CI that it can't detect the errors in the report.
So I think it would be better to add such a check in our CI. (It may be some command like `jupyter nbconvert  workflow_by_code.ipynb`)

Would you like to contribute to this feature in this PR? 

Otherwise, @SunsetWolf lf will help with this feature.

**Comment by lerit** [comment]
I have fix the CI error.
@you-n-g

**Comment by you-n-g** [comment]
Thanks for your

**Pull request merged**
