### PR TITLE
fix some typo in doc/comments

### PR DESCRIPTION
**Pull request by qianyun210603**
## Description
Fix some typo in doc/comments.
Resolve some lint warning.

## Motivation and Context
improve code quality

## How Has This Been Tested?

- [ ] Pass the test by running: `pytest qlib/tests/test_all_pipeline.py` under upper directory of `qlib`.
- [ ] If you are adding a new feature, test on your own test scripts.

## Screenshots of Test Results (if appropriate):
1. Pipeline test:
2. Your own tests:

## Types of changes

- [ ] Fix bugs
- [ ] Add new feature
- [x] Update documentation

### CODE REVIEW

**Comment by you-n-g** [comment]
Thanks for your contribution.
Please fix the CI error. 
image

**Comment by qianyun210603** [comment]
> Thanks for your contribution. Please fix the CI error. image

A quick question please.
Why my black forces spaces before and after operator `**`
image
but the qlib CI forces no spaces? Do you have any clue that how my black should be configured to be consistent with CI? Or it's version inconsistency?

Thanks!

**Comment by you-n-g** [comment]
@qianyun210603  I think this is a problem with the black version.
You can `pip install -U black` to upgrade your black to check if it works.

**Comment by you-n-g** [comment]
It looks great now.
Thanks

**Pull request merged**
