### PR TITLE
bug fix

### PR DESCRIPTION
**Pull request by ArtificialZeng**
## How Has This Been Tested?

- [x] Pass the test by running: `pytest qlib/tests/test_all_pipeline.py` under upper directory of `qlib`.
- [ ] If you are adding a new feature, test on your own test scripts.

## Screenshots of Test Results (if appropriate):
1. Pipeline test:
2. Your own tests:

## Types of changes

- [x] Fix bugs
- [ ] Add new feature
- [ ] Update documentation

### CODE REVIEW

**Comment by ArtificialZeng** [comment]
@you-n-g Thks, How about now?

**Comment by ArtificialZeng** [comment]
@you-n-g  This is the bug fix of issues/1238, So many developer has encountered this https://github.com/microsoft/qlib/issues/1238#issuecomment-1214136339

**Comment by you-n-g** [comment]
I think the error is caused by  [incomplete installation of Qlib](https://github.com/microsoft/qlib/issues/1238#issuecomment-1214147569)
Can you reproduce this error after correctly installing Qlib?

**Comment by ArtificialZeng** [comment]
> I think the error is caused by  [incomplete installation of Qlib](https://github.com/microsoft/qlib/issues/1238#issuecomment-1214147569)
> Can you reproduce this error after correctly installing Qlib?

https://github.com/microsoft/qlib/issues/1238
so, why the others also get 'imcomplete installation'

**Comment by SunsetWolf** [comment]
I see that there is only one line of code added to this PR, I have tested it and found that even without this line the code still runs correctly, how can I reproduce your problem?

**Pull request closed without merging**
