### PR TITLE
Reformat example data names: use `{region}_data` for 1-day data, and `{region}_data_1min` for 1-min data

### PR DESCRIPTION
**Pull request by cning112**
## Description
Use the same name for 1min data

## Motivation and Context
The same data has two names, meaning the same data needs to be downloaded twice to run some examples.

## How Has This Been Tested?
- not needed
- 

## Screenshots of Test Results (if appropriate):
1. Pipeline test:
2. Your own tests:

## Types of changes

- [x] Fix bugs
- [ ] Add new feature
- [ ] Update documentation

### CODE REVIEW

**Comment by you-n-g** [comment]
@cning112 Thanks for your contribution.

I found a lot of commands with different format
image

Would you like to format them to the same path? 
For example, `qlib_cn_1min` is a good name.

**Comment by you-n-g** [comment]
Besides ...
image

Users from the community will be grateful to you :P

**Comment by cning112** [comment]
sure, will make the change in the next commit. Thanks

**Comment by cning112** [comment]
Actually I think the `qlib_` prefix can be removed from the example data names. `{region}_{freq}` should suffice. What do you think? @you-n-g

**Comment by you-n-g** [comment]
@cning112  Yes. Removing the redundant prefix make it simpler
Besides making it simpler, it will be better to make the name consistent with the previous directory to be compatible.
I think keeping "~/.qlib/qlib_data/cn_data" for 1-day data will be more friendly to old users

**Comment by you-n-g** [comment]
@cning112   Please check the Paths in CI workflows
https://github.com/microsoft/qlib/tree/main/.github/workflows

Thanks

**Comment by you-n-g** [comment]
It looks great! Thanks so much!

**Pull request merged**
