### PR TITLE
solve VERSION.txt bug

### PR DESCRIPTION
**Pull request by b4thesunrise**
## Description

change .gitignore file
add back version,txt
## Motivation and Context

https://github.com/microsoft/qlib/issues/731

solve the problem of install qlib with pip install .
## How Has This Been Tested?
- [ ] Pass the test by running: `pytest qlib/tests/test_all_pipeline.py` under upper directory of `qlib`.
- [ ] If you are adding a new feature, test on your own test scripts.

## Screenshots of Test Results (if appropriate):
1. Pipeline test:
2. Your own tests:

## Types of changes

- [ ] Fix bugs
- [ ] Add new feature
- [ ] Update documentation

### CODE REVIEW

**Comment by zhupr** [comment]
@b4thesunrise Hi,
When installing from source (`python setup.py develop/install`) will automatically copy `src/VERSION.txt` to `src/qlib`: https://github.com/microsoft/qlib/blob/main/setup.py#L20

**Comment by zhupr** [comment]
@b4thesunrise Hi,
`pip install <source>` will not execute the `copyfile` in `setup.py`.
Can you help to change the "version" of `qlib` to something like "pip", refer to: https://github.com/pypa/pip/blob/main/setup.py#L28

**Comment by b4thesunrise** [comment]
> @b4thesunrise Hi, `pip install <source>` will not execute the `copyfile` in `setup.py`. Can you help to change the "version" of `qlib` to something like "pip", refer to: https://github.com/pypa/pip/blob/main/setup.py#L28

Hi! I am willing to offer help, so the problem is `pip install <source>`  will cause the error of the lack of version.txt since the copy, so we want to get the version with function like `get version` in pip instead of use `copyfile`?

**Comment by zhupr** [comment]
> > @b4thesunrise Hi, `pip install <source>` will not execute the `copyfile` in `setup.py`. Can you help to change the "version" of `qlib` to something like "pip", refer to: https://github.com/pypa/pip/blob/main/setup.py#L28
> 
> Hi! I am willing to offer help, so the problem is `pip install <source>` will cause the error of the lack of version.txt since the copy, so we want to get the version with function like `get version` in pip instead of use `copyfile`?

Yes, you need to implement a `get_version` function to get the version from `qlib/__init__.py`

**Comment by b4thesunrise** [comment]
> > > @b4thesunrise Hi, `pip install <source>` will not execute the `copyfile` in `setup.py`. Can you help to change the "version" of `qlib` to something like "pip", refer to: https://github.com/pypa/pip/blob/main/setup.py#L28
> > 
> > 
> > Hi! I am willing to offer help, so the problem is `pip install <source>` will cause the error of the lack of version.txt since the copy, so we want to get the version with function like `get version` in pip instead of use `copyfile`?
> 
> Yes, you need to implement a `get_version` function to get the version from `qlib/__init__.py`

got it, will work on it

**Comment by b4thesunrise** [comment]
have already followed the style of pypi and use black format, please give a review :)

**Comment by you-n-g** [comment]
@b4thesunrise  It looks great! 
Thanks so much for your contribution.
Welcome to become Qlib's [contributor](https://github.com/microsoft/qlib/graphs/contributors)!!

**Comment by b4thesunrise** [comment]
> @b4thesunrise It looks great! Thanks so much for your contribution. Welcome to become Qlib's [contributor](https://github.com/microsoft/qlib/graphs/contributors)!!

Thanks! My pleasure!

**Pull request merged**
