### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by saintmalik**
## Description

Made corrections to the typos i found in the documentations.

## Types of changes

- [ ] Fix bugs
- [ ] Add new feature
- [x] Update documentation

### CODE REVIEW

**Comment by cclauss** [comment]
Did you run https://pypi.org/project/codespell/

**Comment by saintmalik** [comment]
> Did you run https://pypi.org/project/codespell/

Not sure if this is needed, the changes added is just little and its correct or what do you think

**Comment by cclauss** [comment]
$ `codespell`
```
./qlib/CHANGES.rst:33: exising ==> existing
10
./qlib/CHANGES.rst:81: calender ==> calendar
11
./qlib/README.md:313: parrallel ==> parallel
12
./qlib/docs/component/recorder.rst:40: pleaes ==> please
13
./qlib/docs/introduction/quick.rst:34: kown ==> known
14
./qlib/docs/introduction/quick.rst:47: kown ==> known
15
./qlib/docs/hidden/online.rst:222: Followings ==> Following
16
./qlib/docs/hidden/online.rst:250: Followings ==> Following
17
./qlib/docs/hidden/tuner.rst:34: privide ==> provide
18
./qlib/docs/hidden/tuner.rst:221: privide ==> provide
19
./qlib/docs/hidden/tuner.rst:224: privide ==> provide
20
./qlib/docs/hidden/tuner.rst:227: privide ==> provide
21
./qlib/docs/hidden/tuner.rst:277: defination ==> definition
22
./qlib/qlib/data/client.py:60: messsage ==> message
23
./qlib/qlib/data/cache.py:362: Overide ==> Override
24
./qlib/qlib/data/cache.py:448: Overide ==> Override
25
./qlib/qlib/data/cache.py:546: expresion ==> expression
26
./qlib/qlib/data/cache.py:861: Aquire ==> Acquire
27
./qlib/qlib/data/cache.py:1038: calulated ==> calculated
28
./qlib/qlib/data/data.py:1056: reponse ==> response
29
./qlib/qlib/data/data.py:1057: Everytime ==> Every time
30
./qlib/qlib/data/dataset/handler.py:73: retrive ==> retrieve
31
./qlib/qlib/data/dataset/handler.py:527: incase ==> in case
32
./qlib/qlib/data/dataset/processor.py:147: ProcessInf ==> processing
33
./qlib/qlib/data/dataset/__init__.py:375: incase ==> in case
34
./qlib/qlib/data/dataset/__init__.py:375: flaot ==> float
35
./qlib/qlib/contrib/evaluate.py:54: commmon ==> common
36
./qlib/qlib/contrib/evaluate_portfolio.py:41: postion ==> position
37
./qlib/qlib/contrib/evaluate_portfolio.py:45: postions ==> positions
38
./qlib/qlib/contrib/data/handler.py:43: ProcessInf ==> processing
39
./qlib/qlib/contrib/tuner/tuner.py:92: spcific ==> specific
40
./qlib/qlib/contrib/model/pytorch_utils.py:36: Unknow ==> Unknown
41
./qlib/qlib/contrib/model/pytorch_tabnet.py:447: transfomer ==> transformer
42
./qlib/qlib/contrib/model/pytorch_tabnet.py:480: feautre ==> feature
43
./qlib/qlib/contrib/model/pytorch_tabnet.py:565: independ ==> independent
44
./qlib/qlib/contrib/model/pytorch_tabnet.py:567: independ ==> independent
45
./qlib/qlib/contrib/model/pytorch_tabnet.py:569: independ ==> independent
46
./qlib/qlib/contrib/model/pytorch_tabnet.py:578: independ ==> independent
47
./qlib/qlib/contrib/model/highfreq_gdbt_model.py:34: threhold ==> threshold
48
./qlib/qlib/contrib/model/highfreq_gdbt_model.py:57: threhold ==> threshold
49
./qlib/qlib/contrib/model/highfreq_gdbt_model.py:59: sigal ==> signal, sigil
50
./qlib/qlib/contrib/model/highfreq_gdbt_model.py:72: threhold ==> threshold
./qlib/qlib/contrib/model/highfreq_gdbt_model.py:72: threhold ==> threshold
./qlib/qlib/contrib/model/pytorch_tra.py:234: OT ==> TO, OF, OR
./qlib/qlib/contrib/model/pytorch_tra.py:665: erros ==> errors
./qlib/qlib/contrib/model/pytorch_tra.py:822: hist ==> heist, his
./qlib/qlib/contrib/model/pytorch_tra.py:872: hist ==> heist, his
./qlib/qlib/contrib/backtest/position.py:193: inital ==> initial
./qlib/qlib/contrib/backtest/account.py:72: substracted ==> subtracted
./qlib/qlib/contrib/backtest/account.py:89: collumns ==> columns
./qlib/qlib/contrib/backtest/backtest.py:27: exchage ==> exchange
./qlib/qlib/contrib/backtest/__init__.py:225: commmon ==> common
./qlib/qlib/contrib/backtest/profit_attribution.py:40: consistant ==> consistent
./qlib/qlib/contrib/backtest/report.py:12: followings ==> following
./qlib/qlib/contrib/backtest/report.py:18: postion ==> position
./qlib/qlib/contrib/online/utils.py:39: te ==> the, be, we, to
./qlib/qlib/contrib/online/executor.py:122: wil ==> will, well
./qlib/qlib/contrib/strategy/strategy.py:101: internel ==> internal
./qlib/qlib/contrib/strategy/strategy.py:160: Seires ==> Series
./qlib/qlib/contrib/strategy/strategy.py:217: minimun ==> minimum
./qlib/qlib/contrib/strategy/strategy.py:217: singal ==> signal, single
./qlib/qlib/contrib/strategy/strategy.py:248: amoutn ==> amount
./qlib/qlib/contrib/strategy/strategy.py:346: singal ==> signal, single
./qlib/qlib/contrib/strategy/cost_control.py:31: amoutn ==> amount
./qlib/qlib/model/riskmodel/shrink.py:198: fro ==> for, from
./qlib/qlib/model/riskmodel/shrink.py:224: fro ==> for, from
./qlib/qlib/model/riskmodel/shrink.py:256: fro ==> for, from
./qlib/qlib/utils/__init__.py:530: wil ==> will, well
./qlib/qlib/workflow/expm.py:101: critera ==> criteria
./qlib/qlib/workflow/cli.py:44: worflow ==> workflow
./qlib/qlib/workflow/record_temp.py:65: occured ==> concurred
./qlib/qlib/workflow/exp.py:91: critera ==> criteria
./qlib/qlib/workflow/task/__init__.py:12: retrive ==> retriever
./qlib/qlib/workflow/task/manage.py:50: serveral ==> several
./qlib/qlib/workflow/task/manage.py:361: Alway ==> Always
./qlib/examples/run_all_model.py:201: parrallel ==> parallel
./qlib/examples/run_all_model.py:243: aruments ==> arguments
./qlib/examples/run_all_model.py:312: erros ==> errors
./qlib/examples/benchmarks/TFT/data_formatters/base.py:35: defintions ==> definitions
./qlib/examples/benchmarks/TFT/libs/hyperparam_opt.py:257: definining ==> defining
./qlib/examples/benchmarks/TFT/libs/hyperparam_opt.py:259: numer ==> number
./qlib/examples/benchmarks/TFT/libs/hyperparam_opt.py:333: serach ==> search
./qlib/examples/benchmarks/TFT/libs/tft_model.py:345: Retuns ==> Returns
./qlib/examples/benchmarks/TFT/libs/tft_model.py:1123: faciliate ==> facilitate
./qlib/examples/benchmarks/TFT/libs/tft_model.py:1126: algined ==> aligned
./qlib/examples/benchmarks/TRA/Reports.ipynb:580: OT ==> TO, OF, OR
./qlib/examples/benchmarks/TRA/README.md:60: scipts ==> scripts, skips
./qlib/examples/benchmarks/TRA/src/model.py:127: postive ==> positive
./qlib/examples/benchmarks/TRA/src/model.py:168: postive ==> positive
./qlib/examples/benchmarks/TRA/src/model.py:487: erros ==> errors
./qlib/examples/highfreq/highfreq_ops.py:176: shoud ==> should
./qlib/scripts/README.md:4: Downlaod ==> Download
./qlib/scripts/data_collector/utils.py:363: informations ==> information
./qlib/scripts/data_collector/cn_index/collector.py:28: BA ==> BY, BE
./qlib/scripts/data_collector/cn_index/collector.py:30: BA ==> BY, BE
./qlib/scripts/data_collector/fund/collector.py:106: enouhg ==> enough
```

**Comment by saintmalik** [comment]
> $ `codespell`
> 
> ```
> ./qlib/CHANGES.rst:33: exising ==> existing
> 10
> ./qlib/CHANGES.rst:81: calender ==> calendar
> 11
> ./qlib/README.md:313: parrallel ==> parallel
> 12
> ./qlib/docs/component/recorder.rst:40: pleaes ==> please
> 13
> ./qlib/docs/introduction/quick.rst:34: kown ==> known
> 14
> ./qlib/docs/introduction/quick.rst:47: kown ==> known
> 15
> ./qlib/docs/hidden/online.rst:222: Followings ==> Following
> 16
> ./qlib/docs/hidden/online.rst:250: Followings ==> Following
> 17
> ./qlib/docs/hidden/tuner.rst:34: privide ==> provide
> 18
> ./qlib/docs/hidden/tuner.rst:221: privide ==> provide
> 19
> ./qlib/docs/hidden/tuner.rst:224: privide ==> provide
> 20
> ./qlib/docs/hidden/tuner.rst:227: privide ==> provide
> 21
> ./qlib/docs/hidden/tuner.rst:277: defination ==> definition
> 22
> ./qlib/qlib/data/client.py:60: messsage ==> message
> 23
> ./qlib/qlib/data/cache.py:362: Overide ==> Override
> 24
> ./qlib/qlib/data/cache.py:448: Overide ==> Override
> 25
> ./qlib/qlib/data/cache.py:546: expresion ==> expression
> 26
> ./qlib/qlib/data/cache.py:861: Aquire ==> Acquire
> 27
> ./qlib/qlib/data/cache.py:1038: calulated ==> calculated
> 28
> ./qlib/qlib/data/data.py:1056: reponse ==> response
> 29
> ./qlib/qlib/data/data.py:1057: Everytime ==> Every time
> 30
> ./qlib/qlib/data/dataset/handler.py:73: retrive ==> retrieve
> 31
> ./qlib/qlib/data/dataset/handler.py:527: incase ==> in case
> 32
> ./qlib/qlib/data/dataset/processor.py:147: ProcessInf ==> processing
> 33
> ./qlib/qlib/data/dataset/__init__.py:375: incase ==> in case
> 34
> ./qlib/qlib/data/dataset/__init__.py:375: flaot ==> float
> 35
> ./qlib/qlib/contrib/evaluate.py:54: commmon ==> common
> 36
> ./qlib/qlib/contrib/evaluate_portfolio.py:41: postion ==> position
> 37
> ./qlib/qlib/contrib/evaluate_portfolio.py:45: postions ==> positions
> 38
> ./qlib/qlib/contrib/data/handler.py:43: ProcessInf ==> processing
> 39
> ./qlib/qlib/contrib/tuner/tuner.py:92: spcific ==> specific
> 40
> ./qlib/qlib/contrib/model/pytorch_utils.py:36: Unknow ==> Unknown
> 41
> ./qlib/qlib/contrib/model/pytorch_tabnet.py:447: transfomer ==> transformer
> 42
> ./qlib/qlib/contrib/model/pytorch_tabnet.py:480: feautre ==> feature
> 43
> ./qlib/qlib/contrib/model/pytorch_tabnet.py:565: independ ==> independent
> 44
> ./qlib/qlib/contrib/model/pytorch_tabnet.py:567: independ ==> independent
> 45
> ./qlib/qlib/contrib/model/pytorch_tabnet.py:569: independ ==> independent
> 46
> ./qlib/qlib/contrib/model/pytorch_tabnet.py:578: independ ==> independent
> 47
> ./qlib/qlib/contrib/model/highfreq_gdbt_model.py:34: threhold ==> threshold
> 48
> ./qlib/qlib/contrib/model/highfreq_gdbt_model.py:57: threhold ==> threshold
> 49
> ./qlib/qlib/contrib/model/highfreq_gdbt_model.py:59: sigal ==> signal, sigil
> 50
> ./qlib/qlib/contrib/model/highfreq_gdbt_model.py:72: threhold ==> threshold
> ./qlib/qlib/contrib/model/highfreq_gdbt_model.py:72: threhold ==> threshold
> ./qlib/qlib/contrib/model/pytorch_tra.py:234: OT ==> TO, OF, OR
> ./qlib/qlib/contrib/model/pytorch_tra.py:665: erros ==> errors
> ./qlib/qlib/contrib/model/pytorch_tra.py:822: hist ==> heist, his
> ./qlib/qlib/contrib/model/pytorch_tra.py:872: hist ==> heist, his
> ./qlib/qlib/contrib/backtest/position.py:193: inital ==> initial
> ./qlib/qlib/contrib/backtest/account.py:72: substracted ==> subtracted
> ./qlib/qlib/contrib/backtest/account.py:89: collumns ==> columns
> ./qlib/qlib/contrib/backtest/backtest.py:27: exchage ==> exchange
> ./qlib/qlib/contrib/backtest/__init__.py:225: commmon ==> common
> ./qlib/qlib/contrib/backtest/profit_attribution.py:40: consistant ==> consistent
> ./qlib/qlib/contrib/backtest/report.py:12: followings ==> following
> ./qlib/qlib/contrib/backtest/report.py:18: postion ==> position
> ./qlib/qlib/contrib/online/utils.py:39: te ==> the, be, we, to
> ./qlib/qlib/contrib/online/executor.py:122: wil ==> will, well
> ./qlib/qlib/contrib/strategy/strategy.py:101: internel ==> internal
> ./qlib/qlib/contrib/strategy/strategy.py:160: Seires ==> Series
> ./qlib/qlib/contrib/strategy/strategy.py:217: minimun ==> minimum
> ./qlib/qlib/contrib/strategy/strategy.py:217: singal ==> signal, single
> ./qlib/qlib/contrib/strategy/strategy.py:248: amoutn ==> amount
> ./qlib/qlib/contrib/strategy/strategy.py:346: singal ==> signal, single
> ./qlib/qlib/contrib/strategy/cost_control.py:31: amoutn ==> amount
> ./qlib/qlib/model/riskmodel/shrink.py:198: fro ==> for, from
> ./qlib/qlib/model/riskmodel/shrink.py:224: fro ==> for, from
> ./qlib/qlib/model/riskmodel/shrink.py:256: fro ==> for, from
> ./qlib/qlib/utils/__init__.py:530: wil ==> will, well
> ./qlib/qlib/workflow/expm.py:101: critera ==> criteria
> ./qlib/qlib/workflow/cli.py:44: worflow ==> workflow
> ./qlib/qlib/workflow/record_temp.py:65: occured ==> concurred
> ./qlib/qlib/workflow/exp.py:91: critera ==> criteria
> ./qlib/qlib/workflow/task/__init__.py:12: retrive ==> retriever
> ./qlib/qlib/workflow/task/manage.py:50: serveral ==> several
> ./qlib/qlib/workflow/task/manage.py:361: Alway ==> Always
> ./qlib/examples/run_all_model.py:201: parrallel ==> parallel
> ./qlib/examples/run_all_model.py:243: aruments ==> arguments
> ./qlib/examples/run_all_model.py:312: erros ==> errors
> ./qlib/examples/benchmarks/TFT/data_formatters/base.py:35: defintions ==> definitions
> ./qlib/examples/benchmarks/TFT/libs/hyperparam_opt.py:257: definining ==> defining
> ./qlib/examples/benchmarks/TFT/libs/hyperparam_opt.py:259: numer ==> number
> ./qlib/examples/benchmarks/TFT/libs/hyperparam_opt.py:333: serach ==> search
> ./qlib/examples/benchmarks/TFT/libs/tft_model.py:345: Retuns ==> Returns
> ./qlib/examples/benchmarks/TFT/libs/tft_model.py:1123: faciliate ==> facilitate
> ./qlib/examples/benchmarks/TFT/libs/tft_model.py:1126: algined ==> aligned
> ./qlib/examples/benchmarks/TRA/Reports.ipynb:580: OT ==> TO, OF, OR
> ./qlib/examples/benchmarks/TRA/README.md:60: scipts ==> scripts, skips
> ./qlib/examples/benchmarks/TRA/src/model.py:127: postive ==> positive
> ./qlib/examples/benchmarks/TRA/src/model.py:168: postive ==> positive
> ./qlib/examples/benchmarks/TRA/src/model.py:487: erros ==> errors
> ./qlib/examples/highfreq/highfreq_ops.py:176: shoud ==> should
> ./qlib/scripts/README.md:4: Downlaod ==> Download
> ./qlib/scripts/data_collector/utils.py:363: informations ==> information
> ./qlib/scripts/data_collector/cn_index/collector.py:28: BA ==> BY, BE
> ./qlib/scripts/data_collector/cn_index/collector.py:30: BA ==> BY, BE
> ./qlib/scripts/data_collector/fund/collector.py:106: enouhg ==> enough
> ```

looks like i have alot to fix in here👀👀

**Comment by you-n-g** [comment]
@saintmalik   It looks great! 
Thanks for your  efforts
If you would like to fix further typos, you can create another pull request.

**Comment by saintmalik** [comment]
> @saintmalik It looks great!
> Thanks for your efforts
> If you would like to fix further typos, you can create another pull request.

Okay thanks, i will open a pull request for the fix of others also.

**Comment by cclauss** [comment]
CAUTION: Codespell is not perfect so please review each instance to be sure it should be changed.

**Comment by saintmalik** [comment]
Definitely

**Pull request merged**
