### PR TITLE
Add PRef operator (#988)

### PR DESCRIPTION
**Pull request by Chaoyingz**
## Description

Added `PRef` operator to support querying pit data for a specified reporting period.

## Motivation and Context

See #988 .

## How Has This Been Tested?

- [ ] Pass the test by running: `pytest qlib/tests/test_all_pipeline.py` under upper directory of `qlib`.
- [x] If you are adding a new feature, test on your own test scripts.

## Screenshots of Test Results (if appropriate):
1. Pipeline test:
2. Your own tests:
image

## Types of changes

- [ ] Fix bugs
- [x] Add new feature
- [ ] Update documentation

### CODE REVIEW

**Comment by you-n-g** [comment]
Hi,  @Chaoyingz
This implementation looks really clean and smart!
But I think I misled you by giving [the example ](https://github.com/microsoft/qlib/issues/988#issuecomment-1074797066) 

I come up with another idea to make it implemented with less code (PRef may not be necessary. We just need to enhance the PFeature)
https://github.com/Chaoyingz/qlib/pull/2

Looking forward for your comments about it

**Comment by Chaoyingz** [comment]
Hi, @you-n-g 
I think `PFeature` should be a feature rather than an expression, no additional parameters should be added to the feature.
How about extending an existing `P` expression directly? like `P($$roewa_q, 201901)`.

**Comment by you-n-g** [comment]
@Chaoyingz  
I think both implementations are good enough but not perfect.
- The previous version will make `PFeature` more complex
- The current version will make `load` function more complex. 

We are trying to introduce minimal complexity (fewer methods, fewer arguments in the interface) into the framework when adding new features.
Instead, if the complexity is added to a concrete subclass, it would keep the framework clean.

And I come up with another option just now. How about adding a subclass for `PFeature` which support an extra `period` argument?  (e.g. changing PF to such a subclass from an alias)


I think all the above solutions are good enough. You can choose the one you like :)

**Comment by Chaoyingz** [comment]
@you-n-g 
I think `PFeature` is a feature (corresponding to the file name), and `P` is an operator. If you want to build a feature dynamically, it is better to use an operator. So pref is the better choice.

**Comment by you-n-g** [comment]
Hi， @Chaoyingz  
I agree with you
Please add more docs for `load` https://github.com/microsoft/qlib/blob/main/qlib/data/base.py#L157 to describe the `period` argument.

I think your next step looks very reasonable.
By such design, maybe the performance of PIT be boosted a lot.

**Comment by Chaoyingz** [comment]
@you-n-g 👌

**Comment by you-n-g** [comment]
It looks great!

**Pull request merged**
