### PR TITLE
Fixed code quality issues

### PR DESCRIPTION
**Pull request by withshubh**
### Description
Hi :wave: 
I ran the [DeepSource](https://deepsource.io) analysis on the forked copy of this repo and found some interesting [code quality issues](https://deepsource.io/gh/withshubh/qlib/issues/?category=recommended).

### Motivation and Context
Some of the issues I have fixed boost minor performance and a few removes the anti-patterns in code.

### Types of changes

- [x] Fix bugs
- [ ] Add new feature
- [ ] Update documentation

### Summary of changes

- Removed length check in favour of truthiness of the object
- Removed unnecessary use of comprehension
- Removed methods with unnecessary super delegation
- Used literal syntax to create data structure
- Refactored unnecessary `else` / `elif` when `if` block has a `continue` statement
- Refactored the comparison involving `not`
- Added .deepsource.toml file

### CODE REVIEW

**Comment by you-n-g** [comment]
@withshubh  Thanks for your  PR,  could you please fix the code style by `python -m black .  -l 120`

**Comment by withshubh** [comment]
Hey @Derek-Wds :wave: 

The fixes in this PR were made using DeepSource Auto-fix feature.

Can you give DeepSource a try on this repo? :sparkles: 
The repo already contains the configuration file. All you need to do is Signup [here](https://deepsource.io/signup) and then activate analysis [here](https://deepsource.io/gh/microsoft/qlib/).

Activating analysis will help you to continuously analyze the repo for code quality issues and you can fix most of the fix using auto-fix feature.

**Comment by withshubh** [comment]
Hi @you-n-g @Derek-Wds :wave: 

Did you try out DeepSource? I'd like to get your feedback :sparkles:

**Comment by you-n-g** [comment]
Hi @withshubh 
Thanks for your adivce.
I setup it just now. But I'm not sure if it is right.

image

**Comment by withshubh** [comment]
Hi @you-n-g 

Follow these steps:
- Install DeepSource on your repository [here](https://deepsource.io/signup).
- Activate analysis [here](https://deepsource.io/gh/microsoft/qlib/).
- you don't need to create the `.deepsource.toml` config file since the repo already has one through this PR.

And there you go :sparkling_heart:

**Comment by you-n-g** [comment]
@withshubh 
Thanks so much! 
DeepSource is really  a powerful tool.
I can't manage the account of microsoft.  But I install DeepSource on my personal account. 

It has been installed [here](https://deepsource.io/gh/you-n-g/qlib/)

**Pull request merged**
