### PR TITLE
Plot enhancement

### PR DESCRIPTION
**Pull request by qianyun210603**
## Description
1. Use `rangebreaks` parameter in plotly to handle gaps in datetime axises. (Fix `# FIXME: support HIGH-FREQ`)
2. Able to plot both `IC` and `RankIC` in `model_performance_graph`.
3. Horizontally layout the bar plots in `risk_analysis_graph` for better looking.
New style
image
v.s. Old style
image
5. Some improvement in plot style

## Motivation and Context
Improve the report graphs.

## How Has This Been Tested?

Create a simple fake `pred_label` df
```python
from pandas.tseries.offsets import CustomBusinessHour
import pandas as pd
import numpy as np
from qlib.contrib.report import analysis_model, analysis_position

cbh = CustomBusinessHour(start=["09:30", "13:00"], end=["11:30", "15:00"])
dt_idx = pd.date_range("2022-12-01", "2022-12-10", freq=cbh)
fake_label_df = pd.DataFrame(np.random.randn(392, 2)*0.01, index=pd.MultiIndex.from_product([dt_idx.to_list(), list("abcdefghigklmn")], names=['datetime', 'instrument']), columns=['label', 'score'])
analysis_model.model_performance_graph(fake_label_df, show_nature_day=False)
```
see the result as expected
image

## Screenshots of Test Results (if appropriate):
1. Pipeline test:
6. Your own tests:

## Types of changes

- [x] <s>Fix bugs</s> Enhancement
- [ ] Add new feature
- [ ] Update documentation

### CODE REVIEW

**Comment by qianyun210603** [comment]
@you-n-g do you mind review please?

**Review by you-n-g — COMMENTED** [review]
Thanks. 
The new feature and graph look really nice :)

**Comment by qianyun210603** [comment]
@you-n-g 
pytest fails in rl module which looks weird since my change should have nothing to do with it.

**Comment by you-n-g** [comment]
Thanks! 
It looks great!

**Pull request merged**
